# Generated by Django 4.2.16 on 2025-11-25 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policestation',
            name='is_online',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='policestation',
            name='response_time',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='policestation',
            name='safety_rating',
            field=models.FloatField(default=4.5),
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('badge_number', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, upload_to='officers/')),
                ('is_available', models.BooleanField(default=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.policestation')),
            ],
        ),
    ]
