# Generated by Django 4.2.16 on 2025-11-25 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosalert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livetracking',
            name='sos_alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergency.sosalert'),
        ),
    ]
